
package com.enrique.xmlservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XmlPortType", targetNamespace = "http://example.com/xmlservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XmlPortType {


    /**
     * 
     * @param result
     * @param date
     * @param code
     * @param outputParams
     * @param name
     * @param inputParams
     * @param action
     * @param time
     * @param type
     * @param user
     */
    @WebMethod(action = "http://example.com/xmlservice/doAction")
    @RequestWrapper(localName = "doAction", targetNamespace = "http://example.com/xmlservice", className = "com.example.xmlservice.XmlRequest")
    @ResponseWrapper(localName = "doActionResponse", targetNamespace = "http://example.com/xmlservice", className = "com.example.xmlservice.XmlResponse")
    public void doAction(
        @WebParam(name = "user", targetNamespace = "http://example.com/xmlservice")
        String user,
        @WebParam(name = "type", targetNamespace = "http://example.com/xmlservice")
        String type,
        @WebParam(name = "action", targetNamespace = "http://example.com/xmlservice")
        String action,
        @WebParam(name = "name", targetNamespace = "http://example.com/xmlservice")
        String name,
        @WebParam(name = "inputParams", targetNamespace = "http://example.com/xmlservice")
        Params inputParams,
        @WebParam(name = "code", targetNamespace = "http://example.com/xmlservice", mode = WebParam.Mode.OUT)
        Holder<String> code,
        @WebParam(name = "result", targetNamespace = "http://example.com/xmlservice", mode = WebParam.Mode.OUT)
        Holder<String> result,
        @WebParam(name = "date", targetNamespace = "http://example.com/xmlservice", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> date,
        @WebParam(name = "time", targetNamespace = "http://example.com/xmlservice", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> time,
        @WebParam(name = "outputParams", targetNamespace = "http://example.com/xmlservice", mode = WebParam.Mode.OUT)
        Holder<Params> outputParams);

}
