
package com.enrique.xmlservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XmlService", targetNamespace = "http://example.com/xmlservice", wsdlLocation = "file:/C:/git-enrique/xml-gateway/src/main/wsdl/XmlService.wsdl")
public class XmlService
    extends Service
{

    private final static URL XMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException XMLSERVICE_EXCEPTION;
    private final static QName XMLSERVICE_QNAME = new QName("http://example.com/xmlservice", "XmlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/git-enrique/xml-gateway/src/main/wsdl/XmlService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLSERVICE_WSDL_LOCATION = url;
        XMLSERVICE_EXCEPTION = e;
    }

    public XmlService() {
        super(__getWsdlLocation(), XMLSERVICE_QNAME);
    }

    public XmlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLSERVICE_QNAME, features);
    }

    public XmlService(URL wsdlLocation) {
        super(wsdlLocation, XMLSERVICE_QNAME);
    }

    public XmlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLSERVICE_QNAME, features);
    }

    public XmlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XmlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XmlPortType
     */
    @WebEndpoint(name = "XmlPort")
    public XmlPortType getXmlPort() {
        return super.getPort(new QName("http://example.com/xmlservice", "XmlPort"), XmlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XmlPortType
     */
    @WebEndpoint(name = "XmlPort")
    public XmlPortType getXmlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/xmlservice", "XmlPort"), XmlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLSERVICE_EXCEPTION!= null) {
            throw XMLSERVICE_EXCEPTION;
        }
        return XMLSERVICE_WSDL_LOCATION;
    }

}
